ALTER TABLE "ContractTemplate"
ADD COLUMN "pdfFilePath" TEXT NOT NULL DEFAULT '',
ADD COLUMN "pdfFileUrl" TEXT NOT NULL DEFAULT '',
ADD COLUMN "pdfFileName" TEXT NOT NULL DEFAULT '',
ADD COLUMN "pdfMimeType" TEXT NOT NULL DEFAULT 'application/pdf',
ADD COLUMN "pageCount" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN "fields" JSONB NOT NULL DEFAULT '[]';

ALTER TABLE "ContractTemplate"
ALTER COLUMN "content" SET DEFAULT '';

ALTER TABLE "Contract"
ADD COLUMN "pdfFilePath" TEXT NOT NULL DEFAULT '',
ADD COLUMN "pdfFileUrl" TEXT NOT NULL DEFAULT '',
ADD COLUMN "pdfFileName" TEXT NOT NULL DEFAULT '',
ADD COLUMN "pdfMimeType" TEXT NOT NULL DEFAULT 'application/pdf',
ADD COLUMN "pageCount" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN "fields" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN "values" JSONB NOT NULL DEFAULT '{}',
ADD COLUMN "submittedAt" TIMESTAMP(3);

ALTER TABLE "Contract"
ALTER COLUMN "content" SET DEFAULT '';
